export const ADD_RECIPE = 'ADD_RECIPE';
export const LOAD_RECIPES = 'LOAD_RECIPES';
export const LOAD_RECIPES_SUCCESS = 'LOAD_RECIPES_SUCCESS';

export const LOAD_RECIPE = 'LOAD_RECIPE';
export const LOAD_RECIPE_SUCCESS = 'LOAD_RECIPE_SUCCESS';

export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';

export const CHANGE_TITLE = 'CHANGE_TITLE';

export const ON_AUTH_START = 'ON_AUTH_START';
export const ON_AUTH_SUCCESS = 'ON_AUTH_SUCCESS';
export const ON_AUTH_LOG_OUT = 'ON_AUTH_LOG_OUT';