export const ADD_RECIPE = 'ADD_RECIPE';
export const LOAD_RECIPES = 'LOAD_RECIPES';
export const LOAD_RECIPES_SUCCESS = 'LOAD_RECIPES_SUCCESS';

export const LOAD_RECIPE = 'LOAD_RECIPE';
export const LOAD_RECIPE_SUCCESS = 'LOAD_RECIPE_SUCCESS';